name: Build Windows x86_64

on:
  workflow_dispatch:
  push:
    tags:
      - 'telluride-build-*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --no-cache-dir astroid
          python -m pip install --upgrade --no-cache-dir pylint
          python -m pip install --upgrade --no-cache-dir yt_dlp
          python -m pip install --upgrade --no-cache-dir pyinstaller

      - name: Run pylint
        shell: bash
        run: |
          python -m pylint --max-line-length=350 telluride.py

      - name: Build with PyInstaller
        shell: bash
        run: |
          pyinstaller --onefile --noupx telluride.py
          mv dist/telluride.exe .

      - name: Organize artifact
        shell: bash
        run: |
          TAG_NAME="${{ github.ref_name }}"
          if [ -z "$TAG_NAME" ] || [ "$TAG_NAME" = "${{ github.ref }}" ]; then
            TAG_NAME="manual-build"
          fi
          mkdir -p "$TAG_NAME"
          mv telluride.exe "$TAG_NAME/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: telluride_windows_x86_64
          path: ${{ github.ref_name != '' && github.ref_name || 'manual-build' }}
          retention-days: 90
